name = "tyjx-landing"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

# 环境变量（明文）
# API_SECRET 请在 Dashboard 中单独添加为 Secret
[vars]
JUMP_DOMAINS = "tyjxnf0skf9h.cc,tyjxlh2wyxr9.cc,tyjxhotpzixm.cc"
